### ISSUE TITLE
Plugin not found in VSCode marketplace

### ISSUE THREAD

**Issue by ssine** [mistzzt/vscode-elsa-lang#1]
Hi, I cannot find this plugin on VS Code marketplace by searching elsa, how can I install it?

**Comment by mistzzt** [comment]
I didn't publish the plugin to the marketplace- so you have to build and install it as a `.vsix`. Instructions here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Also, you're welcome to make contributions (e.g., submit to the marketplace, pack it as a `.vsix`) if you'd like to.
